apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments
  labels:
    app: payments
spec:
  replicas: {{ .Values.payments.replicas }}
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
        - name: payments
          image: {{ .Values.payments.image }}
          imagePullPolicy: Never
          ports:
            - containerPort: 8082
          env:
            - name: PAYMENT_FAILURE_RATE
              value: "{{ .Values.payments.failureRate }}"
            - name: PAYMENT_LATENCY_MS
              value: "{{ .Values.payments.latencyMs }}"
          livenessProbe:
            httpGet:
              path: /health
              port: 8082
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
            failureThreshold: {{ .Values.probes.liveness.failureThreshold }}
          readinessProbe:
            httpGet:
              path: /health
              port: 8082
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
            failureThreshold: {{ .Values.probes.readiness.failureThreshold }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: payments
spec:
  type: ClusterIP
  selector:
    app: payments
  ports:
    - port: 8082
      targetPort: 8082
